Mam 189 sniffer refactor
Mamoru-Foundation/mamoru-core pull request #24
Opened 2023-02-16 13:08 UTC by fgmamoru

2023-02-16 13:16 UTC, sokyrko requested changes

2023-02-16 13:16 UTC, sokyrko commented on mamoru-sniffer-c/headers.h
>  extern "C" {
Looks like unrelated changes in this file.

2023-02-16 13:16 UTC, sokyrko commented on mamoru-sniffer/src/sniffer.rs
> +        chain_type: &Vec<ChainType>,
In this code you pass a reference and then copy the underlying data. Pass by value instead: `Vec<ChainType>`.

2023-02-16 13:16 UTC, sokyrko commented on mamoru-sniffer/src/sniffer.rs
> +            chain_type = self.chain_type[0].as_str_name(),
`chain_type`'s len may be 0 here. It's better to show all of them.

2023-02-16 13:16 UTC, sokyrko commented on mamoru-sniffer/src/sniffer.rs
> +            .list_daemons(self.chain_type[0]) // TODO: support multiple chain types, not sure what to do here.
A single sniffer supports a single chain type, as it reads a single blockchain network. I think `self.chain_type` should not be `Vec`.

2023-02-16 13:16 UTC, sokyrko commented on mamoru-sniffer/src/validation_chain/message_client.rs
> +    pub async fn register_sniffer(&self, chains: Vec<ChainType>) -> ClientResult<()> {
A single sniffer supports a single chain type, as it reads a single blockchain network.

2023-03-01 10:39 UTC, fgmamoru commented on mamoru-sniffer-c/headers.h
>  extern "C" {
This seems to be related with Cargo fmt and clippy

2023-03-01 11:08 UTC, sokyrko reviewed
Thanks for the code. I've left a few more comments

2023-03-01 11:08 UTC, sokyrko commented on mamoru-core/src/daemon/mod.rs
> +        true
Remove this method, it's not relevant anymore.

2023-03-01 11:08 UTC, sokyrko commented on mamoru-sniffer/Cargo.toml
> +uuid = "1.3.0"
`uuid` should be in `[dev-dependencies]` section as it is used for tests only

2023-03-01 11:08 UTC, sokyrko commented on mamoru-sniffer/src/validation_chain/message_client.rs
> +        relay: DaemonRelay,
I believe DaemonRelay is optional parameter

2023-03-01 11:08 UTC, sokyrko commented on mamoru-sniffer/src/validation_chain/message_client.rs
> +                chains: chain_vec,
`chains: vec![Chain { chain_type: chain.into() }]`

2023-03-01 11:08 UTC, sokyrko commented on mamoru-sniffer/src/validation_chain/proto.rs
> +            &value.daemon_metadata.unwrap().content.unwrap().query[0]
Do we have a follow up task to fix this?

2023-03-01 11:08 UTC, sokyrko commented on mamoru-sniffer/tests/validation_chain_tests/sniffer.rs
> +async fn register_active_daemon(
It should be called just `register_daemon`, as they all active now

2023-03-01 11:08 UTC, sokyrko commented on Readme.md
> +## Install development dependencies
Please don't change the layout.

2023-03-01 11:08 UTC, sokyrko commented on mamoru-core/src/blockchain_data/mod.rs
> -        self.now
Is `self.now` still required?

2023-03-02 10:31 UTC, fgmamoru commented on mamoru-sniffer/src/validation_chain/message_client.rs
> +        relay: DaemonRelay,
daemonRelay can be set as type NONE, but seems to be mandatory

2023-03-02 10:33 UTC, fgmamoru commented on mamoru-sniffer/src/validation_chain/proto.rs
> +            &value.daemon_metadata.unwrap().content.unwrap().query[0]
yes

2023-03-02 11:54 UTC, fgmamoru commented on mamoru-core/src/blockchain_data/mod.rs
> -        self.now
removed

2023-03-02 11:54 UTC, fgmamoru commented on mamoru-sniffer/src/validation_chain/message_client.rs
> +                chains: chain_vec,
done in previous line

2023-03-02 11:55 UTC, sokyrko approved these changes

2023-03-02 11:55 UTC, merged